/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.readyready15728.learning_java.ch02;

public class HelloWorld {
    public static void main(String[] args) {
        System.out.println("Hello world!");
    }
}
